version: '3.6'

services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

  web:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    links:
      - db
    user: "1000:1000"
